---
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: ${rootArtifactId}-silo
  labels:
    team: CHANGEME
    tier: silo
    app: ${rootArtifactId}-silo

spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0

  selector:
    matchLabels:
      app: ${rootArtifactId}-silo

  template:
    metadata:
      name: ${rootArtifactId}-silo
      labels:
        team: CHANGEME
        tier: silo
        app: ${rootArtifactId}-silo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/prometheus"

    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: silo
        image: "074509403805.dkr.ecr.eu-west-1.amazonaws.com/${rootArtifactId}-silo:{{.gitCommitID}}"
        imagePullPolicy: Always
        env:
        - name: SILO_PROFILE
          value: kubernetes
        - name: SILO_JAVA_ARGS
          value: >
            -Xms300M
            -Xmx300M
            -XX:MaxMetaspaceSize=128m
            -XX:CompressedClassSpaceSize=32m
            -XX:ReservedCodeCacheSize=128M
            -XX:+UseG1GC
            {{ if eq .clusterName "production" }}
            -javaagent:/usr/local/newrelic/newrelic.jar
            -Dnewrelic.config.app_name=${rootArtifactId}-silo
            -Dnewrelic.config.license_key=CHANGEME
            {{ end }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1024m
            memory: 768Mi
          requests:
            cpu: 128m
            memory: 768Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 1
