---
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: ${rootArtifactId}-silo
  labels:
    team: ${team}
    tier: silo
    app: ${rootArtifactId}-silo

spec:
  rules:
  - host: ${rootArtifactId}-silo.{{.clusterName}}.rebuy.cloud
    http:
     paths:
     - path: /
       backend:
         serviceName: ${rootArtifactId}-silo
         servicePort: 80
