---
apiVersion: v1
kind: Service

metadata:
  name: ${rootArtifactId}-silo
  labels:
    team: ${team}
    tier: silo
    app: ${rootArtifactId}-silo

spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ${rootArtifactId}-silo
