stage: sandbox

server:
    port: 0

clients:
    permissionClient:
        host: customer-silo.localhost

remoteTokenServices:
    endpoint: http://customer-silo.localhost/oauth/check_token

consul:
    agent: 127.0.0.1
