server:
    port: 0

spring:
    datasource:
      url: jdbc:CHANGEME
      host: CHANGEME
      port: CHANGEME
      username: CHANGEME
      password: CHANGEME

clients:
    customerClient:
        host: http://customer-silo.localhost

    permissionClient:
        host: customer-silo.localhost

remoteTokenServices:
    endpoint=http://customer-silo.localhost/oauth/check_token
