stage: dc1

server:
    port: 8080

clients:
    permissionClient:
        host: customer-silo.default.svc.cluster.local.

remoteTokenServices:
    endpoint: customer-silo.default.svc.cluster.local.

messaging:
    host: rabbitmq.default.svc.cluster.local
    user: CHANGEME
    password: CHANGEME
