stage: vagrant

server:
    port: 0
    max-http-header-size: 32768

spring:
    datasource:
        url: jdbc:postgresql://${spring.application.name}.postgres.service.${stage}.consul/rebuy
        username: ${spring.application.name}
        password: ${databasePassword}
        hikari:
            maximum-pool-size: 3

    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

    application:
        name: ${rootArtifactId}

clients:
    permissionClient:
        clientId: ${spring.application.name}
        secret: ${clientSecret}
        host: customer-silo.vg
        port: 80
        keepAliveDurationMs: 300000

flyway:
    baseline-version: 0
    baseline-on-migrate: true
    locations: classpath:db.migration, classpath:db.common
    schemas: flyway_migrations
    table: ${flywayTableName}

permissions:
    cache:
        duration: 24
        timeunit: h

remoteTokenServices:
    clientId: ${spring.application.name}
    secret: ${clientSecret}
    endpoint: customer-silo.vg
    cacheDuration: 10
    cacheTimeUnit: m
    cacheSize: 100

consul:
    name: ${spring.application.name}-silo
    agent: 192.168.33.10
    siloPort: ${server.port}

messaging:
    host: ${spring.application.name}.rabbitmq.service.${stage}.consul
    virtualHost:
    exchange: rebuy
    durable: true
    autoDelete: false
    user:
    password:
    consumerExchange: rebuy
    publisherExchange: rebuy

endpoints:
    prometheus:
        sensitive: false
