stage: dc1

clients:
    permissionClient:
        host: customer-silo.default.svc.cluster.local.

remoteTokenServices:
    endpoint: customer-silo.default.svc.cluster.local.

messaging:
    user: CHANGEME
    password: CHANGEME
