server:
    port: 0

spring:
    datasource:
        url: jdbc:CHANGEME

clients:
    customerClient:
        host: customer-silo.proxy.dc1.rebuy

    permissionClient:
        host: customer-silo.proxy.dc1.rebuy

remoteTokenServices:
    endpoint: http://customer-silo.proxy.dc1.rebuy/oauth/check_token
