stage: dc1

server:
    port: 0

clients:
    permissionClient:
        host: customer-silo.proxy.dc1.rebuy

remoteTokenServices:
    endpoint: http://customer-silo.proxy.dc1.rebuy/oauth/check_token

consulClient:
    agent: 127.0.0.1
