stage: vagrant

server:
    port: 0
    max-http-header-size: 32768

spring:
    datasource:
        url: jdbc:CHANGEME://${spring.config.name}.CHANGEME.service.${stage}.consul/CHANGEME
        username: CHANGEME
        password: CHANGEME
        maximum-pool-size: 3

    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    config:
        name: ${rootArtifactId}

clients:
    permissionClient:
        clientId: ${spring.config.name}
        secret: CHANGEME
        host: customer-silo.vg
        port: 80
        keepAliveDurationMs: 300000

flyway:
    baseline-version: 0
    baseline-on-migrate: true
    locations: classpath:db.migration, classpath:db.common
    schemas: flyway_migrations
    table: CHANGEME

permissions:
    cache:
        duration: 24
        timeunit: h

remoteTokenServices:
    clientId: ${spring.config.name}
    secret: CHANGEME
    endpoint: customer-silo.vg

consul:
    name: ${spring.config.name}-silo
    agent: 192.168.33.10
    siloPort: ${server.port}

messaging:
    host: ${spring.config.name}.rabbitmq.service.${stage}.consul
    virtualHost:
    exchange: rebuy
    durable: true
    autoDelete: false
    user:
    password:
    consumerExchange: rebuy
    publisherExchange: rebuy

endpoints:
    prometheus:
        sensitive: false
