spring:
    datasource:
        # TODO: dont forget to CHANGE the url
        url: jdbc:MYSQL_OR_POSTGRES_OR...
        poolSize: 20

clients:
    customerClient:
        host: http://customer-silo.proxy.dc1.rebuy
