server:
    port: 8080

spring:
    datasource:
        # TODO: dont forget to CHANGE the url
        url: jdbc:MYSQL_OR_POSTGRES_OR...
        user: CHANGEME
        password: CHANGEME
        poolSize: 3
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

clients:
    common:
        readTimeout: 5000
        connectTimeout: 5000
        oauthToken: SOMEUUID4

    customerClient:
        host: http://customer-silo.vg

    permissionClient:
        clientId: ${rootArtifactId}
        secret: CHANGEME
        host: customer-silo.vg
        port: 80
        keepAliveDurationMs: 300000

flyway:
    locations: classpath:db.migration, classpath:db.common
    baseLineOnMigrate: true

permissions:
    cache:
        duration: 10
        timeunit: s

remoteTokenServices:
    clientId=${rootArtifactId}
    secret=CHANGEME
    endpoint=http://customer-silo.vg/oauth/check_token
