silo:
  mailerRecipients:
    - 'CHANGEME'

docker:
  upstreamProjects:
    - 'base-image-builder-maven-docker'
  mailerRecipients:
    - 'CHANGEME'
  buildScript: 'deployment/bin/build'
  dockerFilePaths:
    - 'deployment/docker/Dockerfile'
  repository: ${rootArtifactId}-silo
